name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main  # roda o deploy no push para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.11.0'  # ou outra versão que você usa

    - name: Clean Cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install prisma --force

    - name: Install dependencies
      run: npm install typescript --force
      
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      run: npm run build

    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }} "username"
      run: |
        # Adicionar chave privada ao SSH agent
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        
        # Transferir arquivos para a VPS
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./build/ $USER@$HOST:/var/www/html/

        # Reiniciar o servidor Apache
        ssh -i ~/.ssh/id_rsa $USER@$HOST 'sudo systemctl restart apache2'
