name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main  # roda o deploy no push para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.11.0'  # ou outra versão que você usa

    - name: Clean Cache
      run: npm cache clean --force

    - name: Install prisma
      run: npm install prisma --force

    - name: Install typescript
      run: npm install typescript --force
      
    - name: Install others dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build

    # Configurar a chave SSH no agente para permitir o acesso ao servidor
    - name: Prepare SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa_hostinger
        chmod 600 ~/.ssh/id_rsa_hostinger

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ~/.ssh/id_rsa_hostinger

    # Fazer o deploy dos arquivos para o servidor Hostinger
    - name: Deploy to Hostinger
      env:
        HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
        HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./build/ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.DEPLOY_PATH }}
