name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main  # roda o deploy no push para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.11.0'  # ou outra versão que você usa

    - name: Clean Cache
      run: npm cache clean --force

    - name: Install prisma
      run: npm install prisma --force

    - name: Install typescript
      run: npm install typescript --force
      
    - name: Install others dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build

    # Convertendo a chave SSH para um formato compatível
    - name: Prepare SSH Key
      run: |
        echo "${{ secrets.HOSTINGER_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa_no_pass
        chmod 600 ~/.ssh/id_rsa_no_pass

    # Configurando o ssh-agent para usar a chave privada convertida
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to Hostinger
      env:
        HOSTINGER_HOST: ${{ secrets.HOST }}
        HOSTINGER_USER: ${{ secrets.USERNAME }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./build/ $HOSTINGER_USER@$HOSTINGER_HOST:$DEPLOY_PATH
